name: NodeJS with Parcel

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build
              run: |
                  yarn
                  yarn build

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: spatium
                  path: dist
